version: '3.8'

services:
  #########################################
  #   Setup Database container
  #########################################
  database:
    container_name: municipalidad-database-prod
    image: mysql:8.3.0
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD_ROOT}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT_HOST}:${DB_PORT}"
    volumes:
      - municipalidad-prod-db:/var/lib/mysql
    networks:
      - municipalidad-app-network-prod
  #########################################
  #   Setup Laravel App container
  #########################################
  app:
    depends_on:
      - database
    container_name: municipalidad-backend-prod
    image: ${DOCKER_HUB_USERNAME}/${DOCKER_HUB_APP_IMAGE}:prod
    build:
      context: .
      target: production
    volumes:
      - .:/var/www
      - ./docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh:ro
    ports:
      - "${BACKEND_HOST_PORT}:${BACKEND_CONTAINER_PORT}"
    environment:
      - APP_ENV="production"
      - APP_NAME=${APP_NAME}
      - DB_CONNECTION=${DB_CONNECTION}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    networks:
      - municipalidad-app-network-prod
networks:
  municipalidad-app-network-prod:
volumes:
  municipalidad-prod-db: